### ISSUE TITLE
Says I'm missing the config file?

### ISSUE THREAD

**Issue by qrpike** [gilbitron/Cardash#1]
```
module.js:338
    throw err;
          ^
Error: Cannot find module './config.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/qrpike/Sites/Cardash/cardash.js:7:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by mrSidX** [comment]
I am having the same issue. What goes into the config file and is there any documentation on setting this up? Thanks

**Comment by nourmed** [comment]
I think he missed uploadin the file coz in the cardash.js points that the config.js exists in the same directory
